# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-26 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20170126_0458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='developer',
        ),
    ]
