# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-08 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=2)),
                ('mes', models.CharField(max_length=2)),
                ('anio', models.CharField(max_length=4)),
            ],
        ),
    ]
