# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-08 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_auto_20170208_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.CharField(max_length=200)),
                ('longitud', models.CharField(max_length=200)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.Key')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.Periodo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.Servicio')),
            ],
        ),
    ]
