# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='key',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='servicio',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
