# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0007_auto_20170209_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Llamadas_Consultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.CharField(max_length=200)),
                ('longitud', models.CharField(max_length=200)),
                ('costo_premium', models.CharField(default=None, max_length=4)),
                ('costo_magna', models.CharField(default=None, max_length=4)),
                ('tiempo_minutos', models.CharField(default=None, max_length=6)),
                ('hora', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='developer.Hora')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.Key')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.Periodo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.Servicio')),
            ],
        ),
    ]
